export const insertWord = [
    { sentence: "Hola, me * Juana Serrano", answer: "llamo"},
    { sentence: "Número 1 en el * del turismo", answer: "sector"},
    { sentence: "Shakira es una * de Barcelona", answer: "cantante"},
    { sentence: "Valencia es una * de España", answer: "ciudad"},
    { sentence: "El jamón * un producto de Cuba", answer: "es"},
    { sentence: "El ron es un producto * Perú", answer: "de"},
    { sentence: "Soy * Alemania", answer: "de"},
    { sentence: "Busco personas * practicar español", answer: "para"},
    { sentence: "Mi meta: trabajar en una * internacional", answer: "empresa"},
    { sentence: "Necesito español para hablar * mis colegas", answer: "con"},
    { sentence: "* la guitarra", answer: "toca"},
    { sentence: "¿Qué * hablas?", answer: "idiomas"},
    { sentence: "Me llamo Marta y esta es Paula. * Comercio y Marketing.", answer: "estudiamos"},
    { sentence: "¿Cuál es tu * de teléfono?", answer: "número"},
    { sentence: "Soy de Zaragoza y * en Madrid", answer: "vivo"},
    { sentence: "Esudio Turismo * la Universidad Complutense", answer: "en"},
    { sentence: "Gracias a mis prácticas en el * de Marketing de la cadena...", answer: "departamento"},
    { sentence: "Mi trabajo * muy interesante", answer: "es"},
    { sentence: "Tener * con empresas", answer: "contacto"},
    { sentence: "Organiza seminarios * los empleados", answer: "para"},
    { sentence: "Los productos * cocinar paella son el número 1", answer: "para"},
    { sentence: "Nuestros productos * también en países como India y Estados Unidos", answer: "están"},
    { sentence: "Me * mucho cocinar y leer", answer: "gusta"},
    { sentence: "¿Cuántas * comes carne?", answer: "veces"},
    { sentence: "En el centro * Madrid", answer: "de"},
    { sentence: "¿Tiene una mesa * para el lunes?", answer: "libre"},
    { sentence: "¿Hay menú * dia?", answer: "del"},
    { sentence: "Es la una * media", answer: "y"},
    { sentence: "Desayuno * los días", answer: "todos"},
    { sentence: "Barcelona es una ciudad atractiva * hacer negocios", answer: "para"},
    { sentence: "En Barcelona * muchos bares y restaurantes", answer: "hay"},
    { sentence: "0 simplemente para pasear por sus barrios, su * antiguo y sus zonas peatonales", answer: "casco"},
    { sentence: "Barcelona es famosa en todo el mundo por los * Olímpicos de 1992 y por el FC Barcelona", answer: "Juegos"},
    { sentence: "En la ciudad y en sus alrededores hay muchas posibilidades para * deporte", answer: "hacer"},
    { sentence: "El metro * 12 lineas y es rápido y barato", answer: "tiene"},
    { sentence: "La * de autobús está a la derecha de la parada de taxis", answer: "parada"},
    { sentence: "En grandes ciudad * La Paz..", answer: "como"},
    { sentence: "Toma la primera calle a * derecha", answer: "la"},
    { sentence: "Tienes que tomar * autobús", answer: "el"},
    { sentence: "¿Donde * la Sagrada Familia?", answer: "está"},
    { sentence: "En mi trabajo * que viajar mucho y hablar con clientes.", answer: "tengo"},
    { sentence: "Estoy en casa, leo un libro o pongo la televisión para * fútbol", answer: "var"},
    { sentence: "Los señores Elizondo buscan un hotel * descansar", answer: "para"},
    { sentence: "A la señora Elizondo * encanta jugar al tenis", answer: "le"},
    { sentence: "¿* de estos problemas crees que es más frecuente en un hotel?", answer: "Cuál"},
    { sentence: "Perdón por las *", answer: "molestias"},
    { sentence: "Te disculpas, explicas y ofreces una *", answer: "solución"},
    { sentence: "El personal de recepción ha * muy amable", answer: "sido"},
    { sentence: "Gracias * el cuestionario que nos ha enviado", answer: "por"}
]
