export const muyMucho = [
    { sentence: "* bien", answer: "muy"},
    { sentence: "Sr. Navarro, * gente asocia la paella con la empresa Carmencita.", answer: "mucho"},
    { sentence: "La niña del logo está en las cocinas de * familias", answer: "mucho"},
    { sentence: "Su cocina es * creativa", answer: "Muy"},
    { sentence: "Es morena, no * alta y delgada", answer: "Muy"},
    { sentence: "Es una persona encantadora y * trabajadora", answer: "Muy"},
    { sentence: "Es * productivo", answer: "Muy"},
    { sentence: "Es muy caótico", answer: "Muy"},
    { sentence: "Me gusta * cocinar y leer", answer: "Mucho"},
    { sentence: "* veces no ceno", answer: "Mucho"},
    { sentence: "Me gusta * la fruta", answer: "Mucho"},
    { sentence: "* empresas de todo el mundo tienen aquí sus oficinas.", answer: "Mucho"},
    { sentence: "En Barcelona hay * bares y restaurantes.", answer: "Mucho"},
    { sentence: "Hay * obras del arquitecto Antonio Gaudí", answer: "Mucho"},
    { sentence: "No hay * edificios antiguos", answer: "Mucho"},
    { sentence: "Hay un parque * tranquilo", answer: "Muy"},
    { sentence: "Moverse por Madrid es * fácil", answer: "Muy"},
    { sentence: "Un metro * moderno", answer: "Muy"},
    { sentence: "Madrid tiene 170 rutas de autobuses públicos y * trenes regionales que van al centro", answer: "Mucho"},
    { sentence: "Los autobuses son un poco lentos porque hay * tráfico", answer: "Mucho"},
    { sentence: "Hay pocos aparcamientos en el centro y siempre hay * problemas de tráfico", answer: "Mucho"},
    { sentence: "La gente no usa * la bicicleta en la ciudad", answer: "Mucho"},
    { sentence: "Barcelona es una ciudad * atractiva", answer: "Muy"},
    { sentence: "En Barcelona hay * restaurantes", answer: "Muchos"},
    { sentence: "El bar La Mureneta está * cerca", answer: "Muy"},
    { sentence: "Es * difícil llegar", answer: "Muy"},
    { sentence: "Es un metro * moderno", answer: "Muy"},
    { sentence: "La parada está * cerca", answer: "Muy"},
    { sentence: "No uso * la bicicleta", answer: "Mucho"},
    { sentence: "Mi hermano es * alto", answer: "Muy"},
    { sentence: "Mis calcetines están * sucios", answer: "Muy"},
    { sentence: "Tus amigas son * locas", answer: "Muy"},
    { sentence: "Estoy * enojado", answer: "Muy"},
    { sentence: "Yo hablo * despacio", answer: "Muy"},
    { sentence: "Tú hablas español * bien", answer: "Muy"},
    { sentence: "Sí, *", answer: "Mucho"},
    { sentence: "Sí, * cansado", answer: "Muy"},
    { sentence: "Tengo * trabajo", answer: "Mucho"},
    { sentence: "Hace * calor", answer: "Mucho"},
    { sentence: "Hay * comida en la mesa", answer: "Mucho"},
    { sentence: "Ella tiene * paciencia", answer: "Mucho"},
    { sentence: "Mi hijo tiene * zapatos", answer: "Mucho"},
    { sentence: "Necesito * vasos para la fiesta", answer: "Mucho"},
    { sentence: "Mi hija tiene * amigas", answer: "Mucho"},
    { sentence: "Hay * casas viejas en mi barrio", answer: "Mucho"},
    { sentence: "Estoy muy satisfecho, he comido *", answer: "Mucho"},
    { sentence: "Mi hijo está muy cansado porque estudió *", answer: "Mucho"},
    { sentence: "Mi esposo trabaja *", answer: "Mucho"}
]
