export const serEstar = [
    { sentence: "Esta * la señora Alcántara", answer: "Ser"},
    { sentence: "El señor Navarro * economista", answer: "Ser"},
    { sentence: "* español", answer: "Ser"},
    { sentence: "* de Valencia", answer: "Ser"},
    { sentence: "Carmen * alta y guapa", answer: "Ser"},
    { sentence: "El jersey * negro", answer: "Ser"},
    { sentence: "La corbata * de seda", answer: "Ser"},
    { sentence: "Hoy * lunes", answer: "Ser"},
    { sentence: "* el 2 de Junio", answer: "Ser"},
    { sentence: "* las diez y media", answer: "Ser"},
    { sentence: "* 12 Euro por persona", answer: "Ser"},
    { sentence: "La empresa * de mi padre", answer: "Ser"},
    { sentence: "Dónde * Luis?", answer: "Estar"},
    { sentence: "* en casa", answer: "Estar"},
    { sentence: "Cómo *?", answer: "Estar"},
    { sentence: "* bien", answer: "Estar"},
    { sentence: "La habitación no * limpa", answer: "Estar"},
    { sentence: "La oficina * amueblada", answer: "Estar"},
    { sentence: "La cocina * equipada", answer: "Estar"},
    { sentence: "Yo * Raúl", answer: "Ser"},
    { sentence: "Bob * inglés", answer: "Ser"},
    { sentence: "Andrés * católico", answer: "Ser"},
    { sentence: "Soy profesora * español", answer: "Ser"},
    { sentence: "Ellos * estudiantes", answer: "Ser"},
    { sentence: "Mi padre * jardinero", answer: "Ser"},
    { sentence: "Juanita * bailarina", answer: "Ser"},
    { sentence: "Amalia * inteligente, atrevida, y amable", answer: "Ser"},
    { sentence: "Mi esposo * romántico y cariñoso", answer: "Ser"},
    { sentence: "Hoy * miércoles", answer: "Ser"},
    { sentence: "Ahora * la una", answer: "Ser"},
    { sentence: "* las cinco veinticinco", answer: "Ser"},
    { sentence: "Celia * de España", answer: "Ser"},
    { sentence: "* chocolate es de México", answer: "Ser"},
    { sentence: "Las sillas * de madera", answer: "Ser"},
    { sentence: "Mi anillo * de oro", answer: "Ser"},
    { sentence: "Lynne * mi madre", answer: "Ser"},
    { sentence: "Marcos * mi exnovio", answer: "Ser"},
    { sentence: "Juana * mi jefe", answer: "Ser"},
    { sentence: "Mi abuela * sentada", answer: "Estar"},
    { sentence: "El baño * a la derecha de la sala", answer: "Estar"},
    { sentence: "* en el café ahora y estaremos en el cine en 20 minutos", answer: "Estar"},
    { sentence: "Mi abuelo * en la luna", answer: ""},
    { sentence: "* lavando los platos sucios", answer: "Estar"},
    { sentence: "* leyendo los periódicos", answer: "Estar"},
    { sentence: "Mi bisabuelo * muerto", answer: "Estar"},
    { sentence: "* tan cansada esta mañana", answer: "Estar"},
    { sentence: "Mis niños * enfermos hoy", answer: "Estar"},
    { sentence: "Mi padre * un poco loco", answer: "Estar"},
    { sentence: "* triste", answer: "Estar"},
    { sentence: "Ella * contenta porque recibió unas flores de su novio", answer: "Estar"}
]
